CREATE TABLE IF NOT EXISTS NuevaTabla AS
SELECT 
    p.ID_POSTRE AS IDUsuario,
    lc.NOMBRE AS TipoCoordenada,
    lc.UBICACION AS Coordenada,
    c.NOMBRE AS Arsenal,
    p.NOMBRE AS Dia
FROM POSTRE p
LEFT JOIN COMIDAS c ON p.ID_COMIDAS = c.ID_COMIDAS
LEFT JOIN LOCAL_COMIDAS lc ON c.ID_LCOMIDAS = lc.ID_LCOMIDAS;