CREATE TABLE IF NOT EXISTS DR_USER
(
    UserId INTEGER PRIMARY KEY AUTOINCREMENT,
    NameUser VARCHAR(30) NOT NULL,
    PasswordUser VARCHAR(8) NOT NULL
);

INSERT INTO DR_USER (NameUser,PasswordUser) VALUES ( 'Profe','827ccb0eea8a706c4c34a16891f84e7b' );
INSERT INTO DR_USER (NameUser,PasswordUser) VALUES ( 'dilan.real@epn.edu.ec','0e688dfd210714513f78bf3e807bf0dd' );
INSERT INTO DR_USER (NameUser,PasswordUser) VALUES ( 'Alberto23@gmail.com','c44a471bd78cc6c2fea32b9fe028d30a' );

CREATE TABLE IF NOT EXISTS DR_LOGGIN
(
    LoginLogId INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL,
    LoginTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(UserId) REFERENCES DR_USER(UserId)
);

CREATE TABLE IF NOT EXISTS DR_COORDENADA 
(
    usuarioId INTEGER PRIMARY KEY AUTOINCREMENT,
    
    Geoposicion VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS DR_COORDENADATIPO
(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Tipo VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS DR_ARSENAL
(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    ArsenalTipo VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS DR_HORARIOS
(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Dia VARCHAR(30) NOT NULL,
    Hora VARCHAR(30) NOT NULL
);

SELECT * FROM DR_USER;